pc1 = input().split()
pc2 = input().split()
cod_pc1 = int(pc1[0])
cod_pc2 = int(pc2[0])
nr_pc1 = int(pc1[1])
nr_pc2 = int(pc2[1])
price_pc1 = float(pc1[2])
price_pc2 = float(pc2[2])
total = (nr_pc1 * price_pc1 + nr_pc2 * price_pc2)
print(f'VALOR A PAGAR: R$ {total:.2f}')
