date = input()
date = date.replace('/',' ')
date = date.split()
dd = (date[0])
mm = (date[1])
aa = (date[2])
print('{}/{}/{}'.format(mm,dd,aa))
print('{}/{}/{}'.format(aa,mm,dd))
print('{}-{}-{}'.format(dd,mm,aa))
